package br.com.senac.view;

import br.com.senac.model.Usuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {

    private final Usuario usuarioAutenticado;
    
    public MenuPrincipal(Usuario usuarioAutenticado) {
        this.usuarioAutenticado = usuarioAutenticado;
        initComponents();
        permissoes(usuarioAutenticado);
        
        addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent e){
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para a tela inicial?", "Voltar", JOptionPane.YES_NO_OPTION);
                
                if (opcao == JOptionPane.YES_OPTION){
                    TelaInicial telaInicial = new TelaInicial();
                    telaInicial.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    private void permissoes(Usuario usuarioAutenticado){
        switch(usuarioAutenticado.getTipoUsuario()){
            case "Securitário":
                btnTelaListaUsuarios.setEnabled(false);
                break;
            case "Gerente":
                btnTelaListaUsuarios.setEnabled(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTelaRegistro = new javax.swing.JButton();
        btnTelaListaVendas = new javax.swing.JButton();
        btnTelaListaUsuarios = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu Principal");

        btnTelaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTelaRegistro.setText("Registrar Nova Venda");
        btnTelaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaRegistroActionPerformed(evt);
            }
        });

        btnTelaListaVendas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTelaListaVendas.setText("Lista de Vendas");
        btnTelaListaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaListaVendasActionPerformed(evt);
            }
        });

        btnTelaListaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTelaListaUsuarios.setText("Lista de Usuários do Sistema");
        btnTelaListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaListaUsuariosActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTelaRegistro)
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnTelaListaVendas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnTelaListaUsuarios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnLogout)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(btnTelaRegistro)
                .addGap(18, 18, 18)
                .addComponent(btnTelaListaVendas)
                .addGap(18, 18, 18)
                .addComponent(btnTelaListaUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaRegistroActionPerformed
        TelaRegistro telaRegistro = new TelaRegistro(usuarioAutenticado);
        telaRegistro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaRegistroActionPerformed

    private void btnTelaListaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaListaVendasActionPerformed
        TelaListaVendas telaListaVendas = new TelaListaVendas(usuarioAutenticado);
        telaListaVendas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaListaVendasActionPerformed

    private void btnTelaListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaListaUsuariosActionPerformed
        TelaListaUsuarios telaListaUsuarios = new TelaListaUsuarios(usuarioAutenticado);
        telaListaUsuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaListaUsuariosActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para a tela inicial?", "Voltar", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            TelaInicial telaInicial = new TelaInicial();
            telaInicial.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTelaListaUsuarios;
    private javax.swing.JButton btnTelaListaVendas;
    private javax.swing.JButton btnTelaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
