package br.com.senac.view;

import br.com.senac.controller.UsuarioCtrl;
import br.com.senac.model.Usuario;
import br.com.senac.model.dto.UsuarioDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaListaUsuarios extends javax.swing.JFrame {

    private final Usuario usuarioAutenticado;
    private final UsuarioCtrl controller;
    private DefaultTableModel tableModel;
    
    public TelaListaUsuarios(Usuario usuarioAutenticado) {
        this.controller = new UsuarioCtrl();
        this.usuarioAutenticado = usuarioAutenticado;
        initComponents();
        configurarTabela();
        carregarDados();
        
        addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent e){
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal?", "Voltar", JOptionPane.YES_NO_OPTION);
                
                if (opcao == JOptionPane.YES_OPTION){
                    MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
                    menuPrincipal.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    private void configurarTabela() {
        tableModel = new DefaultTableModel(
            new String[]{"ID", "Username", "Tipo de Usuário"}, 0);
        jTable1.setModel(tableModel);
    }
    
    private void carregarDados() {
        List<UsuarioDTO> usuarios = controller.listarUsuarios();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        usuarios.forEach(u -> model.addRow(new Object[]{
            u.getId(),
            u.getUsername(),
            u.getTipoUsuario()
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemoverUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Lista de Usuários");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRemoverUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRemoverUser.setText("Remover Usuário");
        btnRemoverUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnRemoverUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoverUser)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUserActionPerformed
        int linha = jTable1.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    this, 
                    "Selecione um usuário para remover.", 
                    "Atenção", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Object [] opcao = {"Cancelar", "Confirmar"};
        int confirmacao = JOptionPane.showOptionDialog(
                this, 
                "Esta ação não pode ser desfeita. Confirmar exclusão do usuário?", 
                "Confirmar exclusão", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.WARNING_MESSAGE, 
                null, 
                opcao, 
                opcao[0]);
        
        if(confirmacao == 1){
            Integer id = (Integer) jTable1.getValueAt(linha, 0);
        
            try{
                controller.excluirUsuario(id, usuarioAutenticado.getId());
                carregarDados();
                JOptionPane.showMessageDialog(
                        this, 
                        "Usuário removido com sucesso.", 
                        "Sucesso", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(
                        this, 
                        "Ocorreu um erro: " + e.getMessage(), 
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRemoverUserActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal", "Voltar", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
            menuPrincipal.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverUser;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
